stages:
  - pipeline

pipeline:
  stage: pipeline
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential cmake git unzip  # essential packages for building the project
  script:
    - chmod +x ./install.sh
    - ./install.sh --enable-tests
  cache:
    key: "$CI_COMMIT_REF_NAME"  # allow caching for different branches
    paths:
      - lib/**/*  # cache the lib directory to all levels

