stages:
  - install-and-build
  - test
  - cleanup

variables:
  BUILD_DIR: "build"
  CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
  MAKE_ARGS: "-j$(nproc)"

cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - $BUILD_DIR/
    - lib/

install-and-build:
  stage: install
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential cmake git unzip libssl-dev
  script:
    - chmod +x ./install.sh
    - ./install.sh --enable-tests
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week

test:
  stage: test
  image: gcc:latest
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure
  dependencies:
    - install-and-build

cleanup:
  stage: cleanup
  script:
    - rm -rf $BUILD_DIR